FROM golang:1.22.1-alpine3.18 AS build

WORKDIR /src

COPY go.mod go.sum .
RUN go mod download

COPY . .
RUN go build -o /build/wow-client ./cmd/client

FROM alpine:3.18

COPY --from=build /build/wow-client /usr/local/bin/wow-client

ENTRYPOINT ["/usr/local/bin/wow-client"]